import type {
  ExchangeItem,
  ExchangeTransaction,
  RewardPerformance,
  CatalogStats,
  ReportStats,
} from "../types"

export const INITIAL_CATALOG_STATS: CatalogStats = {
  totalItems: 24,
  activeItems: 18,
  pausedItems: 4,
  totalPointsExchanged: 12450,
}

export const INITIAL_EXCHANGE_ITEMS: ExchangeItem[] = [
  {
    id: "item-1",
    title: "Giảm 15% khóa Speaking",
    sponsor: "CatSpeak",
    pointsCost: 500,
    stockCurrent: 124,
    stockTotal: 500,
    validity: "31/12/2023",
    status: "active",
    applicableCourse: "Khóa học Speaking Pro",
    limitPerStudent: 1,
    startDate: "2023-01-01",
    endDate: "2023-12-31",
  },
  {
    id: "item-2",
    title: "Voucher giảm 100.000đ khóa IELTS",
    sponsor: "CatSpeak",
    pointsCost: 1200,
    stockCurrent: 45,
    stockTotal: 50,
    validity: "Vô thời hạn",
    status: "active",
    applicableCourse: "Khóa Luyện thi IELTS Intensive",
    limitPerStudent: 1,
  },
  {
    id: "item-3",
    title: "Voucher giảm 200.000đ học phí",
    sponsor: "Chủ lớp",
    pointsCost: 800,
    stockCurrent: 0,
    stockTotal: 200,
    validity: "15/10/2023",
    status: "expired",
    applicableCourse: "Tất cả khóa học",
    limitPerStudent: 2,
    startDate: "2023-06-01",
    endDate: "2023-10-15",
  },
  {
    id: "item-4",
    title: "Giảm 25% khóa Luyện thi TOEIC",
    sponsor: "Chủ lớp",
    pointsCost: 1000,
    stockCurrent: 89,
    stockTotal: 100,
    validity: "Vô thời hạn",
    status: "active",
    applicableCourse: "Khóa Luyện thi TOEIC Target 800+",
    limitPerStudent: 1,
  },
]

export const INITIAL_TRANSACTIONS: ExchangeTransaction[] = [
  {
    id: "TXN-20240815-001",
    stt: "01",
    studentName: "Nguyễn Văn An",
    studentEmail: "an.nguyen@email.com",
    rewardTitle: "Voucher giảm 100.000đ khóa IELTS",
    pointsDeducted: 500,
    codeResult: "CAT-XA3F1",
    time: "15/08/2024 - 14:30",
    completedTime: "15/08/2024 - 14:30:25",
    status: "success",
  },
  {
    id: "TXN-20240815-002",
    stt: "02",
    studentName: "Trần Thị Mai",
    studentEmail: "mai.tran@email.com",
    rewardTitle: "Khóa học Kỹ năng giao tiếp",
    pointsDeducted: 1200,
    codeResult: "Lỗi kết nối",
    time: "15/08/2024 - 10:15",
    status: "failed",
    failReason: "Hệ thống đối tác không phản hồi",
  },
  {
    id: "TXN-20240814-003",
    stt: "03",
    studentName: "Lê Hoàng Long",
    studentEmail: "long.le@email.com",
    rewardTitle: "Voucher giảm 75.000đ khóa Writing",
    pointsDeducted: 800,
    codeResult: "CAT-8T2NT",
    time: "14/08/2024 - 16:45",
    completedTime: "14/08/2024 - 16:45:18",
    status: "success",
  },
  {
    id: "TXN-20240814-004",
    stt: "04",
    studentName: "Phạm Minh",
    studentEmail: "minh.pham@email.com",
    rewardTitle: "Giảm 25% khóa Luyện thi TOEIC",
    pointsDeducted: 300,
    codeResult: "Hết tồn kho",
    time: "14/08/2024 - 08:20",
    status: "failed",
    failReason: "Kho voucher tạm thời hết mã khả dụng",
  },
]

export const INITIAL_REPORT_STATS: ReportStats = {
  totalExchanges: 342,
  exchangesGrowth: 12,
  totalPointsSpent: 48500,
  pointsGrowth: 5.2,
  participatingStudents: 128,
  avgPerStudent: 2.6,
  remainingRewards: 1240,
  lowStockCount: 12,
}

export const INITIAL_REWARD_PERFORMANCE: RewardPerformance[] = [
  {
    id: "perf-1",
    title: "Voucher giảm 50% Khóa Tiếng Anh Giao Tiếp",
    pointsCost: 1000,
    exchangeCount: 142,
    totalPointsSpent: 170000,
    remainingStock: 858,
    trend: "up",
  },
  {
    id: "perf-2",
    title: "Voucher giảm 200k Lớp IELTS 7.0+",
    pointsCost: 2000,
    exchangeCount: 89,
    totalPointsSpent: 178000,
    remainingStock: "Vô hạn",
    trend: "stable",
  },
  {
    id: "perf-3",
    title: "Voucher giảm 50.000đ học phí",
    pointsCost: 8000,
    exchangeCount: 45,
    totalPointsSpent: 360000,
    remainingStock: 12,
    trend: "down",
  },
  {
    id: "perf-4",
    title: "Giảm 10% toàn bộ khóa học",
    pointsCost: 15000,
    exchangeCount: 29,
    totalPointsSpent: 435000,
    remainingStock: 36,
    trend: "up",
  },
  {
    id: "perf-5",
    title: "Giảm 25% khóa Luyện thi TOEIC",
    pointsCost: 3500,
    exchangeCount: 28,
    totalPointsSpent: 133000,
    remainingStock: 145,
    trend: "stable",
  },
]

export const TIMELINE_EXCHANGE_DATA = [
  { label: "01/10", value: 15 },
  { label: "05/10", value: 22 },
  { label: "10/10", value: 21 },
  { label: "15/10", value: 28 },
  { label: "20/10", value: 26 },
  { label: "25/10", value: 38 },
  { label: "30/10", value: 32 },
]

export const POPULAR_REWARDS_SEGMENTS = [
  { label: "Khóa học Advanced", value: 45, color: "#EA580C" },
  { label: "Voucher 50%", value: 30, color: "#F59E0B" },
  { label: "Khóa học Basic", value: 15, color: "#910B09" },
  { label: "Khác", value: 10, color: "#475569" },
]
